### PR TITLE
Console display enhancement for BM2SM

### PR DESCRIPTION
**Pull request by sillybear**
Everything is explained in this video:

[demo_vid.zip](https://github.com/SaxxonPike/scharfrichter/files/1683672/demo_vid.zip)

### CODE REVIEW

**Comment by SaxxonPike** [comment]
I like what you've done. However, it should be an optional feature, perhaps enabled via command line, or by asking the user at the beginning. If you make that change, I'll accept and merge.

**Comment by sillybear** [comment]
> ...or by asking the user at the beginning...

Done. Pressing Enter key will instantly convert without user input just like the original.

screenshot_1

**Comment by SaxxonPike** [comment]
This makes it optional for each file individually, but for someone who is converting 300 files (let's say a whole game..) still requires input for every file, which is not ideal. It needs some way to bypass the need for input entirely.

**Comment by sillybear** [comment]
Done.
screenshot_1

**Comment by SaxxonPike** [comment]
Thank you for making the changes I suggested! I'll be merging this now. It will be revisited for code style in the future, much like a lot of the other code in this project.

**Pull request merged**
